config/routes.rb
Rails.application.routes.draw do
  root to: "membership_forms#home"
  get '/form/:id', action: :form, controller: 'membership_forms', to: "membership_forms#form",as: :form
  resources :membership_forms
  get '/home' ,to: "membership_forms#home",as: :home
  resources :roles
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    
    if user.role.name == "Admin" || user.role.name == "Super Admin"
      can [:create,:new,:index,:show,:edit ,:update, :destroy,:home,:form], MembershipForm
    else
      can [:create,:new,:show,:edit,:update,:home,:form], MembershipForm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/membership_form.rb
class MembershipForm < ApplicationRecord
    belongs_to :user,optional: true
    belongs_to :admin,optional: true, :class_name => "User", :foreign_key => 'admin_id'
    mount_uploader :image, ImageUploader
    # validates_uniqueness_of :user_id
    scope :admin_forms ,-> {where.not(admin_id: nil)}

    before_update :change_status

    def change_status
        # if self.status_changed?
        #     # binding.pry
        #     StatusMailer.status_change(self).deliver_now
        # end
        # binding.pry
    end
end

app/models/role.rb
class Role < ApplicationRecord
    has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :role
  has_one :membership_form
  # validates :mobile, presence: true
  # , minimum: 10, maximum: 10
  # has_many :membership_forms
  # , -> (membership_form) {where.not(admin_id: nil)}
  has_many :admin_forms, :foreign_key => "admin_id", :class_name => "MembershipForm"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?
    rescue_from CanCan::AccessDenied do |exception|
        respond_to do |format|
          format.json { head :forbidden, content_type: 'text/html' }
          format.html { redirect_to main_app.root_url, notice: exception.message }
          format.js   { head :forbidden, content_type: 'text/html' }
        end
    end
    protected

    def configure_permitted_parameters
        # Fields for sign up
        devise_parameter_sanitizer.permit(:sign_up, keys: [:mobile,:name, :email, :password,:role_id])
        # Fields for editing an existing account
        # devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :current_password, :gender) }
    end
end

app/controllers/membership_forms_controller.rb
class MembershipFormsController < ApplicationController
  load_and_authorize_resource param_method: :my_sanitizer 
  # ,except: :form
  before_action :set_membership_form, only: [:show, :edit, :update, :destroy,:form]

  # GET /membership_forms
  # GET /membership_forms.json
  def index
    @membership_forms = MembershipForm.all
  end

  # GET /membership_forms/1
  # GET /membership_forms/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf  do 
        render pdf: "membership",template: 'membership_forms/show.html.erb'
      end
    end
  end

  def form
    respond_to do |format|
      format.html
      format.pdf  do 
        render pdf: "membership",template: 'membership_forms/form.html.erb'
      end
    end
  end

  def home
    if current_user.role.name == "Admin" || current_user.role.name == "Super Admin"
      redirect_to membership_forms_path
    else
      @membership_form = current_user.membership_form
    end
  end

  # GET /membership_forms/new
  def new
    # if current_user.role.name == "User"
      @membership_form = MembershipForm.new
    # else
      # redirect_to membership_forms_path
    # end
  end

  # GET /membership_forms/1/edit
  def edit
  end

  # POST /membership_forms
  # POST /membership_forms.json
  def create
    @membership_form = MembershipForm.new(membership_form_params)
    respond_to do |format|
      if @membership_form.save
        format.html { redirect_to @membership_form, notice: 'Membership form was successfully created.' }
        format.json { render :show, status: :created, location: @membership_form }
      else
        format.html { render :new }
        format.json { render json: @membership_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /membership_forms/1
  # PATCH/PUT /membership_forms/1.json
  def update
    respond_to do |format|
      if @membership_form.update(membership_form_params)
        format.html { redirect_to @membership_form, notice: 'Membership form was successfully updated.' }
        format.json { render :show, status: :ok, location: @membership_form }
      else
        format.html { render :edit }
        format.json { render json: @membership_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /membership_forms/1
  # DELETE /membership_forms/1.json
  def destroy
    @membership_form.destroy
    respond_to do |format|
      format.html { redirect_to membership_forms_url, notice: 'Membership form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membership_form
      @membership_form = MembershipForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def membership_form_params
      params.require(:membership_form).permit(:name, :father_name, :mother_name, :age, :dob, :sex, :blood_group, :local_address, :local_pin, :l_mobile_no, :l_tele_no, :kodagu_address, :k_pin, :k_mobile_no, :k_tele_no, :nominee_of_death_fund, :form_date, :applicants_sign, :husband_name, :husbands_mother_name, :wifes_name, :no_family_members, :occupation, :proposer_family_name, :proposer_mobile, :proposer_tele, :proposer_memebership_no, :proposer_sign, :seconder_family_name, :seconder_mobile, :seconder_tele, :seconder_memebership_no, :seconder_sign, :status, :user_id, :membership_fee, :receipt_no, :cash_dd, :receipt_date, :president_sign, :hon_secretary_sign,:admin_id,:image)
    end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/membership_forms_helper.rb
module MembershipFormsHelper
    def options_for_sex
        ['Male','Women']
    end

    def status
        ['Membership Accepted','Under Review','Rejected']
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/membership_forms/_form.html.erb
 <div class="row">
  <div class="col-md-12">
  <h1 style="text-align: center;">KODAVA SAMAJA (R)</h1>
  <p style="text-align: center;">No. 7, 1st Main Road, Vasanthanagar, Bangalore - 560 052
  Phone : 2226 0188 / 2235 1088</p>
          <p style="text-align: center;">APPLICATION FOR MEMBERSHIP</p>
  </div>
</div> 
<%= form_with(model: membership_form, local: true) do |form| %>
  <% if membership_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(membership_form.errors.count, "error") %> prohibited this membership_form from being saved:</h2>

      <ul>
      <% membership_form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class= "container">
  <div class="form-group row">
    <label class="col-sm-4 col-form-label">Name with Initials and Family Name</label>
    <div class="col-sm-8">
      <%= form.text_field :name ,class:"form-control"%>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-4 col-form-label">Father’s Name with Family Name</label>
    <div class="col-sm-8">
      <%= form.text_field :father_name ,class:"form-control"%>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-4 col-form-label">Mother’s Name with Family Name (Thamane)</label>
    <div class="col-sm-8">
    <%= form.text_field :mother_name ,class:"form-control"%>
    </div>
  </div>

  <h4>IF MARRIED</h4>

  <div class="form-group row">
    <label class="col-sm-4 col-form-label">(a) Husband’s Name with Family Name</label>
    <div class="col-sm-8">
    <%= form.text_field :husband_name ,class:"form-control"%>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-4 col-form-label">(b) Husband’s Mother’s Family Name</label>
    <div class="col-sm-8">
    <%= form.text_field :husbands_mother_name  ,class:"form-control"%>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-4 col-form-label">(c) Wife’s Name with Family Name (Thamane) </label>
    <div class="col-sm-8">
      <%= form.text_field :wifes_name  ,class:"form-control"%>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-4 col-form-label">(d) Number of members in the family</label>
    <div class="col-sm-8">
      <%= form.number_field :no_family_members ,class:"form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-4 col-form-label"> (e) Occupation of the Members</label>
    <div class="col-sm-8">
      <%= form.text_field :occupation  ,class:"form-control"%>
    </div>
  </div>

  <%
=begin%>
 <div class="form-group row">
    <label class="col-sm-2 col-form-label">Age</label>
    <div class="col-sm-2">
    <%= form.number_field :age  ,class:"form-control"%>
    </div>
    <label class="col-sm-2 col-form-label">DOB</label>
     <div class="col-sm-2">
    <%= form.date_select :dob ,class:"form-control" %>
    </div>
  </div> 
<%
=end%>

  <div class="form-row">
    <div class="form-group col-md-3">
      <label for="inputCity">Age</label>
       <%= form.number_field :age  ,class:"form-control"%>
    </div>
    <div class="form-group col-md-3">
      <label for="inputState">DOB</label>
      <%= form.text_field :dob ,class:"form-control" %>
    </div>
    <div class="form-group col-md-3">
      <label for="inputZip">Sex</label>
      <br>
      <%= form.select :sex, options_for_sex, :prompt => 'Select One',class: "form-control" %>
    </div>
    <div class="form-group col-md-3">
      <label for="inputZip">Blood Group</label>
      <%= form.text_field :blood_group ,class:"form-control" %>
    </div>
  </div>

  
  <div class="form-group row">
    <%= form.label :local_address %>
    <%= form.text_area :local_address  ,class:"form-control"%>
  </div>

  <div class="form-group row">
    <div class="form-group col-md-4">
      <%= form.label :local_pin %>
      <%= form.number_field :local_pin  ,class:"form-control"%>
    </div>
    <div class="form-group col-md-4">
      <%= form.label :l_mobile_no %>
      <%= form.text_field :l_mobile_no  ,class:"form-control"%>
    </div>

    <div class="form-group col-md-4">
      <%= form.label :l_tele_no %>
      <%= form.text_field :l_tele_no  ,class:"form-control"%>
    </div>
  </div>


  <div class="form-group row">
    <%= form.label :kodagu_address %>
    <%= form.text_area :kodagu_address  ,class:"form-control"%>
  </div>

  <div class="form-group row">
    <div class="form-group col-md-4">
    <%= form.label :k_pin %>
    <%= form.number_field :k_pin  ,class:"form-control"%>
    </div>
    <div class="form-group col-md-4">
      <%= form.label :k_mobile_no %>
      <%= form.text_field :k_mobile_no  ,class:"form-control"%>
    </div>

    <div class="form-group col-md-4">
      <%= form.label :k_tele_no %>
      <%= form.text_field :k_tele_no  ,class:"form-control"%>
    </div>
  </div>


  <div class="form-group row">
    <label class="col-sm-4 col-form-label">Nominee for Death Fund with relationship</label>
    <div class="col-sm-8">
    <%= form.text_field :nominee_of_death_fund  ,class:"form-control"%>
    </div>
  </div>

  <h6>Kindly enroll me as a Life / Associate Member of the Kodava Samaja, Bangalore. I agree to abide by the rules and regulations of the Bye-Law of the Samaja.</h6>

  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Date</label>
    <div class="col-sm-4">
      <%= form.date_select :form_date  ,class:"form-control"%>
    </div>
    <label class="col-sm-2 col-form-label">Sign</label>
    <div class="col-sm-4">
    <%= form.text_field :applicants_sign  ,class:"form-control" %>
    </div>
  </div>

  <%
=begin%>
 <table class="table table-dark">
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <tr> 
    
    </tr>
  </tbody> 
<%
=end%>

  <div class="form-group row">
    <div class="form-group col-md-3">
      <label class=""> Proposer with Family Name </label>
      <%= form.text_field :proposer_family_name  ,class:"form-control"%>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :proposer_mobile %>
      <%= form.text_field :proposer_mobile  ,class:"form-control"%>
      <br>
      <%= form.label :proposer_tele %>
      <%= form.text_field :proposer_tele  ,class:"form-control"%>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :proposer_memebership_no %>
      <%= form.text_field :proposer_memebership_no  ,class:"form-control"%>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :proposer_sign %>
      <%= form.text_field :proposer_sign ,class:"form-control"%>
    </div>
  </div>

  <div class="form-group row">
    <div class="form-group col-md-3">
      <%= form.label :seconder_family_name %>
      <%= form.text_field :seconder_family_name ,class:"form-control"%>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :seconder_mobile %>
      <%= form.text_field :seconder_mobile,class:"form-control" %>
      <br>
      <%= form.label :seconder_tele %>
      <%= form.text_field :seconder_tele ,class:"form-control"%>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :seconder_memebership_no %>
      <%= form.text_field :seconder_memebership_no ,class:"form-control"%>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :seconder_sign %>
      <%= form.text_field :seconder_sign ,class:"form-control"%>
    </div>
  </div>

  <h6>The Proposer and the Seconder should know the full details of the applicant.</h6>

  <div class="form-group row">
    <div class="form-group col-md-3">
      <%= form.label :membership_fee %>
      <%= form.text_field :membership_fee ,class:"form-control"%>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :receipt_no %>
      <%= form.text_field :receipt_no ,class:"form-control"%>
    </div>
  </div>

  <div class="form-group row">
    <div class="form-group col-md-3">
      <%= form.label :cash_dd %>
      <%= form.text_field :cash_dd ,class:"form-control"%>
    </div>
    <div class="form-group col-md-4">
      <%= form.label :receipt_date %>
    <br>
      <%= form.date_select :receipt_date ,class:"form-control"%>
    </div>
    <% if current_user.role.name == "Admin" || current_user.role.name == "Super Admin"  %>
      <div class="form-group col-md-4">
        <%= form.label :status %>
        <%= form.select :status, status, :prompt => 'Select One',class: "form-control" %>
      </div>
        <%= form.hidden_field :admin_id, :value =>  current_user.id,class:"form-control" %>
    <%else%>
      <%= form.hidden_field :user_id, :value =>  current_user.id,class:"form-control" %>
    <% end %>
  </div>

  <%
=begin%>
 <div class="form-group row">
    <%= form.label :user_id %>
    <%= form.number_field :user_id,class:"form-control" %>
  </div> 
<%
=end%>


  <div class="form-group row">
    <div class="form-group col-md-4">
      <%= form.label :president_sign %>
      <%= form.text_field :president_sign ,class:"form-control"%>
    </div>
    <div class="form-group col-md-4">
      <%= form.label :hon_secretary_sign %>
      <%= form.text_field :hon_secretary_sign ,class:"form-control"%>
    </div>
    <div class="form-group col-md-4">
      <%= form.label :image %>
      <%= form.file_field :image ,class:"form-control"%>
  </div>
    </div>
  </div>


  <div class="actions">
    <%= form.submit "Submit",class: "btn btn-primary"%>
    <% if current_user.role.name == "User" %>
      <%= link_to 'Home', home_path ,class: "btn btn-light"%>
      <br>
    <%else%>
      <%= link_to 'Back', membership_forms_path ,class: "btn btn-primary"%>
    <%end%>
    <br>
  </div>
  </div>
<% end %>

app/views/membership_forms/index.html.erb
<%
=begin%>
 <h2 style="text-align: center;">Welcome To KODAVA SAMAJA (R) Member Ship Form</h2>   
<%
=end%>
<div>
<% if user_signed_in? %>
  <p><%= link_to  "Sign Out", destroy_user_session_path , :method => 'delete'%></p>
<%else%>
  <%= link_to  "Sign In" ,user_session_path %>
<%end%>
</div>
<%
=begin%>
 <p id="notice"><%= notice %></p> 
<%
=end%>

    <div class="row">
        <div class="col-sm-6">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row no-gutters">
                    <div class="col-md-6">
                        <div class="card-body">
                            <h5 class="card-title">Hello,<%= current_user.name %></h5>
                            <p><%= current_user.email%></p>
                            <p>Role: <%= current_user.role.name%></p>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <% if current_user.role.name == "Admin" || current_user.role.name == "Super Admin"%>
                            <%= link_to 'Create Membership', new_membership_form_path,class: "btn btn-primary",method: "get",style: "margin-top: 35px" %>
                        <% else %>
                            <p style="text-align: center">If you dont have MemberShip Click  the Button</p>
                            <%= link_to 'Create Membership', new_membership_form_path,class: "btn btn-primary",method: "get",style: "margin-top: 0px" %>
                        <%end%>
                        <p></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <% current_user.admin_forms.each do |membership_form| %>
        <div class="card mb-3" style="max-width: 540px;">
            <div class="row no-gutters">
                <div class="col-md-4">
                <img src="<%= membership_form.image %>" class="card-img" alt="">
                </div>
                <div class="col-md-6">
                    <div class="card-body">
                        <h5 class="card-title"><%= membership_form.name %></h5>
                        <h6 class="card-title"><%= membership_form.father_name %></h6>
                        <h6 class="card-title"><%= membership_form.mother_name %></h6>
                        <h6 class="card-title"><%= membership_form.age %></h6>
                        <p><b>Status:</b> <%= membership_form.status%> </p>
                        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                    </div>
                </div>
                <div class="col-md-2">
                <br>
                    <h5 class="card-title"><%= link_to 'Edit', edit_membership_form_path(membership_form),class: "btn btn-primary" %></h5>
                    <h5 class="card-title"><%= link_to 'Show', membership_form,class: "btn btn-primary" %></h5>
                    <h5 class="card-title"><%= link_to 'print', form_path(membership_form, :format => :pdf ),class: "btn btn-primary", target: :_blank %></h5>
                    <h5 class="card-title"><%= link_to 'Destroy', membership_form, method: :delete, data: { confirm: 'Are you sure?' } ,class: "btn btn-primary"%></h5>
                </div>
            </div>
        </div>
            <%end%>
        </div>
    </div>

app/views/membership_forms/new.html.erb
<%= render 'form', membership_form: @membership_form %>
<%# if current_user.role.name == "User" %>
<%#= link_to 'Home', home_path %>
<%#else%>
<%#= link_to 'Back', membership_forms_path %>
<%#end%>

app/views/membership_forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name with Initials and Family Name:</strong> <%= @membership_form.name %>
</p>

<p>
  <strong>Father's Name with Family Name</strong> <%= @membership_form.father_name %>
</p>

<p>
  <strong>Mother's Name with Family Name (Thamane)</strong> <%= @membership_form.mother_name %>
</p>

IF MARRIED

  <p>
  <strong>(a) Husband's Name with Family Name</strong><%= @membership_form.husband_name %>
</p>

<p>
  <strong>(b) Husband's Mother's Family Name </strong> <%= @membership_form.husbands_mother_name %>
</p>

<p>
  <strong>(c) Wife's Name with Family Name (Thamane)</strong>
  <%= @membership_form.wifes_name %>
</p>
<div class="container">
<div class="row">
  <div class="col">
    <p>
      <strong>d) Number of members in the family</strong>
      <%= @membership_form.no_family_members %>
    </p>
  </div>
  <div class="col">
    <p>
      <strong>(e) Occupation of the Members</strong>
      <%= @membership_form.occupation %>
    </p>
  </div>
</div>

</div>


<p>
  <strong>Age:</strong>
  <%= @membership_form.age %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @membership_form.dob %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @membership_form.sex %>
</p>

<p>
  <strong>Blood group:</strong>
  <%= @membership_form.blood_group %>
</p>

<p>
  <strong>Local address:</strong>
  <%= @membership_form.local_address %>
</p>

<p>
  <strong>Local pin:</strong>
  <%= @membership_form.local_pin %>
</p>

<p>
  <strong>L mobile no:</strong>
  <%= @membership_form.l_mobile_no %>
</p>

<p>
  <strong>L tele no:</strong>
  <%= @membership_form.l_tele_no %>
</p>

<p>
  <strong>Kodagu address:</strong>
  <%= @membership_form.kodagu_address %>
</p>

<p>
  <strong>K pin:</strong>
  <%= @membership_form.k_pin %>
</p>

<p>
  <strong>K mobile no:</strong>
  <%= @membership_form.k_mobile_no %>
</p>

<p>
  <strong>K tele no:</strong>
  <%= @membership_form.k_tele_no %>
</p>

<p>
  <strong>Nominee of death fund:</strong>
  <%= @membership_form.nominee_of_death_fund %>
</p>

<p>
  <strong>Form date:</strong>
  <%= @membership_form.form_date %>
</p>

<p>
  <strong>Applicants sign:</strong>
  <%= @membership_form.applicants_sign %>
</p>



<p>
  <strong>Proposer family name:</strong>
  <%= @membership_form.proposer_family_name %>
</p>

<p>
  <strong>Proposer mobile:</strong>
  <%= @membership_form.proposer_mobile %>
</p>

<p>
  <strong>Proposer tele:</strong>
  <%= @membership_form.proposer_tele %>
</p>

<p>
  <strong>Proposer memebership no:</strong>
  <%= @membership_form.proposer_memebership_no %>
</p>

<p>
  <strong>Proposer sign:</strong>
  <%= @membership_form.proposer_sign %>
</p>

<p>
  <strong>Seconder family name:</strong>
  <%= @membership_form.seconder_family_name %>
</p>

<p>
  <strong>Seconder mobile:</strong>
  <%= @membership_form.seconder_mobile %>
</p>

<p>
  <strong>Seconder tele:</strong>
  <%= @membership_form.seconder_tele %>
</p>

<p>
  <strong>Seconder memebership no:</strong>
  <%= @membership_form.seconder_memebership_no %>
</p>

<p>
  <strong>Seconder sign:</strong>
  <%= @membership_form.seconder_sign %>
</p>

<p>
  <strong>Status:</strong>
  <%= @membership_form.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @membership_form.user_id %>
</p>

<p>
  <strong>Membership fee:</strong>
  <%= @membership_form.membership_fee %>
</p>

<p>
  <strong>Receipt no:</strong>
  <%= @membership_form.receipt_no %>
</p>

<p>
  <strong>Cash dd:</strong>
  <%= @membership_form.cash_dd %>
</p>

<p>
  <strong>Receipt date:</strong>
  <%= @membership_form.receipt_date %>
</p>

<p>
  <strong>President sign:</strong>
  <%= @membership_form.president_sign %>
</p>

<p>
  <strong>Hon secretary sign:</strong>
  <%= @membership_form.hon_secretary_sign %>
</p>
<%#= image_tag  @membership_form.image%>
<img src=<%= @membership_form.image%>/>

<%= link_to 'Edit', edit_membership_form_path(@membership_form) %> |
<%= link_to 'Back', membership_forms_path %>

app/views/roles/edit.html.erb
<h1>Editing Role</h1>

<%= render 'form', role: @role %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Roles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.name %></td>
        <td><%= link_to 'Show', role %></td>
        <td><%= link_to 'Edit', edit_role_path(role) %></td>
        <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Role', new_role_path %>

app/views/roles/new.html.erb
<h1>New Role</h1>

<%= render 'form', role: @role %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @role.name %>
</p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>